[package]
name = "prism"
version = "0.1.0"
authors = ["Dennis van Ee <dennis@vanee.us>"]
edition = "2018"

[dependencies]
num-traits = "0.2.8"
ply-rs = "0.1.2"
simple-error = "0.2.1"
serde_json = "1.0.40"
bitflags = "1.1.0"

# These are needed because rust doesn't have an implace partition
# function or nth_element (in stable) function that I am aware of:
order-stat = "0.1.3"
partition = "0.1.1"