[package]
name = "prism"
version = "0.1.0"
authors = ["Dennis van Ee <dennis@vanee.us>"]
edition = "2018"

[dependencies]
# Prism scene descriptions use TOML
toml = "0.5.6"
# Used all over the place for math and whatnot:
num-traits = "0.2.8"
# Used to load PLY files:
ply-rs = "0.1.2"
simple-error = "0.2.1"
serde_json = "1.0.40"
bitflags = "1.1.0"
arrayvec = "0.4.11"
bumpalo = "2.6.0"

# These are needed because rust doesn't have an implace partition
# function or nth_element (in stable) function that I am aware of:
order-stat = "0.1.3"
partition = "0.1.1"