#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// This includes the internal part of it:
include!(concat!(env!("OUT_DIR"), "/rtcore.rs"));

// Not sure why, but Bindgen didn't define this either:
pub const RTC_INVALID_GEOMETRY_ID: ::std::os::raw::c_uint = ::std::os::raw::c_uint::max_value(); // code was ((unsigned int)-1)

// This is an inline function, so it's not generated by bindgen:
pub fn rtcInitIntersectContext(context: &mut RTCIntersectContext) {
    context.flags = RTCIntersectContextFlags_RTC_INTERSECT_CONTEXT_FLAG_INCOHERENT;
    context.filter = None;
    for id in context.instID.iter_mut() {
        *id = RTC_INVALID_GEOMETRY_ID;
    }
}
