[package]
authors = ["Dennis van Ee <dennis@vanee.us>"]
edition = "2018"
name = "embree"
version = "0.1.0"

[dependencies]
bitflags = "1.2.1"
lazy_static = "1.4.0"
pmath = {path = "../pmath"}

[build-dependencies]
bindgen = "0.54.1"
